### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [D-a-s-h-e-r/EAS#1]
Please update the Readme so that people can understand what the plugin does

**Comment by D-a-s-h-e-r** [comment]
Readme file has been updated with explanation

**Comment by pcav** [comment]
Please also add a proper home page (a link to this repo would suffice).
Thanks.

**Comment by D-a-s-h-e-r** [comment]
Readme txt and html files have been updated with home page link (this repository)

**Comment by NyakudyaA** [comment]
@D-a-s-h-e-r  changelog is empty. Please update it

**Comment by D-a-s-h-e-r** [comment]
Changelog now lists revised items

**Comment by AlisterH** [comment]
You can probably close this ticket.
